server:
  context-path: /show-rt
  port: 8080

spring:
  resources:
    static-locations:classpath:/resources/, classpath:/static/

---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/showrt
    username: test
    password: test123
  jpa:
    database: MYSQL
    show-sql: true
---
spring:
  profiles: prod
  jpa:
    show-sql: false