server:
  context-path: /service-rt
  port: 8081

---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://10.48.193.201:3306/showrt?useUnicode=true&characterEncoding=utf-8
    username: test
    password: test1234
  jpa:
    database: MYSQL
    show-sql: true
zkName: zk-dev

---
spring:
  profiles: online
zkName: zk-online
